FROM ubuntu:22.04

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      ca-certificates openssl build-essential git iptables && \
    update-ca-certificates && \
    git clone --depth 1 https://github.com/wangyu-/udp2raw-tunnel.git /src && \
    make -C /src && install -m755 /src/udp2raw /usr/local/bin/udp2raw && \
    rm -rf /src /var/lib/apt/lists/*

ENTRYPOINT ["udp2raw"]